### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by louispt1** [louispt1/MarketTrader#3]
Some form of database to store active and past trade orders

- Stores trades
- Stores general data to inform trades....

**Comment by milanleonard** [comment]
It seems to be this should probably be two databases, one to store currently active trade orders, which we can imagine to be an order book, and then a database of actual executed trades.

For an MVP, we don't necessarily need to give people the ability to revoke their trade orders, `pull` their orders, but a good way to start doing so might be to attach each order a unique orderid. Unlike traders and products which should be named, this is probability fine to just be sequential, such that it is just the concatenation of traderid-productid-orderid for example.
